# Generated by Django 5.0.1 on 2024-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular_courses',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
